### ISSUE TITLE
build failed on Mac.

### ISSUE THREAD

**Issue by openersoft** [klebs6/surge-rs#1] opened 2023-04-16 04:35 UTC
command : cargo build

output:
error: failed to load manifest for workspace member `~/surge-rs/surge-scene`

Caused by:
  failed to load manifest for dependency `surge-voice`

Caused by:
  failed to load manifest for dependency `surgeosc-wavetable`

Caused by:
  failed to load manifest for dependency `surge-wavetable`

Caused by:
  failed to load manifest for dependency `surge-hound`

Caused by:
  failed to read `~/surge-rs/surge-wavetable/surge-hound/Cargo.toml`

Caused by:
  No such file or directory (os error 2)

**Comment by klebs6** [comment] 2023-04-17 00:19
thanks for letting me know! sorry about that! taking a look now :)

**Comment by klebs6** [comment] 2023-04-17 00:47
ok! fixed by 7f5c494! thanks for letting me know about it!

**Closed** 2023-04-17 00:50 UTC

**Comment by Hangghost** [comment] 2023-06-14 08:29
Hi, I also have problems in building it.
This is my enviroment:
```
> stable-aarch64-apple-darwin (default)
> beta-aarch64-apple-darwin
> nightly-aarch64-apple-darwin
```

When I build first time: `surge-rs % cargo build`
Output:
```
**warning: patch for the non root package will be ignored, specify patch at the workspace root:**
package:   /Users/chenhunglun/Documents/Procjects/Rust /surge-rs/surge-synthesizer/Cargo.toml
workspace: /Users/chenhunglun/Documents/Procjects/Rust /surge-rs/Cargo.toml
**warning: /Users/chenhunglun/Documents/Procjects/Rust /surge-rs/surgefx-chorus/Cargo.toml: unused manifest key: build**
   Compiling autocfg v1.1.0
   ...
   Compiling parking_lot v0.12.1
**error: failed to run custom build command for `libxml v0.3.2`**

Caused by:
  process didn't exit successfully: `/Users/chenhunglun/Documents/Procjects/Rust /surge-rs/target/debug/build/libxml-ae7f6b48ca8a76ad/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBXML_2.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=LIBXML_2.0_STATIC
  cargo:rerun-if-env-changed=LIBXML_2.0_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=LIBXML_2.0_STATIC
  cargo:rerun-if-env-changed=LIBXML_2.0_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  **thread 'main' panicked at 'Could not find libxml2.', /Users/chenhunglun/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libxml-0.3.2/build.rs:38:5**
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /Users/chenhunglun/.cargo/registry/src/index.crates.io-6f17d22bba15001f/packed_simd_2-0.3.8/src/lib.rs:214:1
    |
214 | / #![feature(
215 | |     adt_const_params,
216 | |     repr_simd,
217 | |     rustc_attrs,
...   |
224 | |     custom_inner_attributes,
225 | | )]
    | |__^

error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /Users/chenhunglun/.cargo/registry/src/index.crates.io-6f17d22bba15001f/packed_simd_2-0.3.8/src/lib.rs:219:5
    |
219 |     stdsimd,
    |     ^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /Users/chenhunglun/.cargo/registry/src/index.crates.io-6f17d22bba15001f/packed_simd_2-0.3.8/src/lib.rs:222:5
    |
222 |     core_intrinsics,
    |     ^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
**error: could not compile `packed_simd_2` (lib) due to 3 previous errors**
```

To fix the `error[E0554]: `#![feature]` may not be used on the stable release channel`
I tried `cargo +nightly build`
Output:
warning: patch for the non root package will be ignored, specify patch at the workspace root:
package:   /Users/chenhunglun/Documents/Procjects/Rust /surge-rs/surge-synthesizer/Cargo.toml
workspace: /Users/chenhunglun/Documents/Procjects/Rust /surge-rs/Cargo.toml
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
warning: /Users/chenhunglun/Documents/Procjects/Rust /surge-rs/surgefx-chorus/Cargo.toml: unused manifest key: build
   Compiling autocfg v1.1.0
   ...
   Compiling coreaudio-sys v0.2.12
   Compiling parking_lot v0.12.1
error: failed to run custom build command for `libxml v0.3.2`

Caused by:
  process didn't exit successfully: `/Users/chenhunglun/Documents/Procjects/Rust /surge-rs/target/debug/build/libxml-cdb90275d47f392d/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBXML_2.0_NO_PKG_CONFIG
...
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'Could not find libxml2.', /Users/chenhunglun/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libxml-0.3.2/build.rs:38:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...


Could you give me any ideas?

**Comment by Hangghost** [comment] 2023-06-14 08:39
I have tried the solution from [this](https://github.com/KWARC/rust-libxml)
The solution is 
`$ brew install libxml2 # e.g. version 2.9.12 `
`$ ln -s /usr/local/Cellar/libxml2/2.9.12/lib/libxml2.2.dylib /usr/local/lib/libxml-2.0.dylib`
`$ export LIBXML2=/usr/local/Cellar/libxml2/2.9.12/lib/pkgconfig/libxml-2.0.pc `

I just modified after checking in my terminal:
`$ brew install libxml2 `
`$ export LIBXML2=/**opt/homebrew**/Cellar/libxml2/**2.11.4**/lib/pkgconfig/libxml-2.0.pc `
However, in line 2, I can not find "usr/local/lib/libxml-2.0.dylib"
In /opt/homebrew/lib , I have no libxml2 or libxml files.
